[workspace]
resolver = "2"
members = [
    "crates/nodetool",
    "crates/nodetool-utility",
    "crates/nodetool/tests/plugins/alpha",
    "crates/nodetool/tests/plugins/beta",
    "crates/nodetool/tests/plugins/gamma",
    "crates/nodetool/tests/plugins/delta",
    "examples/plugins/shapes",
    "examples/plugins/text",
    "examples/list-nodes",
    "examples/list-nodes-empty",
    "examples/load-graph",
    "examples/compile-graph",
    "examples/run-node",
    "examples/run-graph",
]
