[package]
name = "nodetool"
version = "0.1.0"
edition = "2021"

[dependencies]
inventory = "0.3"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
uuid = { version = "1", default-features = false, features = ["std", "serde"] }

[dev-dependencies]
test-plugin-alpha = { path = "tests/plugins/alpha" }
test-plugin-beta = { path = "tests/plugins/beta" }
